version: '3.4'

services:
  mssql:
    container_name: ms_sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "kIBWaki8@"
    ports:
      - 1433:1433

  wp.api:
    image: ${DOCKER_REGISTRY-}wpapi
    build:
      context: .
      dockerfile: WP.API/Dockerfile
    depends_on:
      - mssql   